name: spinwheel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bitsdojo_window: ^0.1.6
  confetti: ^0.7.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.1
  gap: ^3.0.1
  get: 4.6.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  msix: ^3.16.7

flutter:
  uses-material-design: true

msix_config:
  display_name: SpinWheel
  logo_path: assets\launcher.png
  msix_version: 1.0.0.0
  install_certificate: false
